### PR TITLE
Using toggle button change theme

### PR DESCRIPTION
**Pull request by sachingowdaac**
This change is [Reviewable](https://reviewable.io/reviews/sachingowdaac/digital-library/5)

### CODE REVIEW

**Review by kpunith8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sachingowdaac/digital-library/5)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @sachingowdaac)

___
*[src/components/navBar.js, line 55 at r1](https://reviewable.io/reviews/sachingowdaac/digital-library/5#-MOoMyYFCj_OdLw8whQn:-MOoMyYFCj_OdLw8whQo:bf2wydl) ([raw file](https://github.com/sachingowdaac/digital-library/blob/c54a3e5801b6c206296b3eac70b032115356f15c/src/components/navBar.js#L55)):*
> ```JavaScript
>           <button
>             className="p-1 rounded-full focus:outline-none focus:shadow-outline focus:border-purple-500 bg-transparent bg-purple-800 text-white hover:bg-purple-500"
>             onClick={() => onThemeChange()}
> ```

No need to invoke the onThemeChange, just pass it as,
```
onClick={onThemeChange}
```
Its already being handled in the App.js

**Comment by sachingowdaac** [comment]
> > _[Reviewable](https://reviewable.io/reviews/sachingowdaac/digital-library/5)_ status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @sachingowdaac)
> 
> _[src/components/navBar.js, line 55 at r1](https://reviewable.io/reviews/sachingowdaac/digital-library/5#-MOoMyYFCj_OdLw8whQn:-MOoMyYFCj_OdLw8whQo:bf2wydl) ([raw file](https://github.com/sachingowdaac/digital-library/blob/c54a3e5801b6c206296b3eac70b032115356f15c/src/components/navBar.js#L55)):_
> 
> > ```js
> >           <button
> >             className="p-1 rounded-full focus:outline-none focus:shadow-outline focus:border-purple-500 bg-transparent bg-purple-800 text-white hover:bg-purple-500"
> >             onClick={() => onThemeChange()}
> > ```
> 
> No need to invoke the onThemeChange, just pass it as,
> 
> ```
> onClick={onThemeChange}
> ```
> 
> Its already being handled in the App.js

**Review by sachingowdaac — COMMENTED** [review]
Removed the invoke

**Review by kpunith8 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sachingowdaac/digital-library/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sachingowdaac)

**Review by kpunith8 — COMMENTED** [review]
Looks good, merge it

> *[Reviewable](https://reviewable.io/reviews/sachingowdaac/digital-library/5#-:-MOootSo6T4woW0bXC7D:bv22dud)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sachingowdaac)

**Pull request merged**
