### PR TITLE
Search feature and css for img

### PR DESCRIPTION
**Pull request by sachingowdaac**
This change is [Reviewable](https://reviewable.io/reviews/sachingowdaac/digital-library/2)

### CODE REVIEW

**Review by sachingowdaac — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sachingowdaac/digital-library/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sachingowdaac)

**Comment by kpunith8** [comment]
___
*[src/components/Home.js, line 11 at r1](https://reviewable.io/reviews/sachingowdaac/digital-library/2#-MMG7jqP300NokKCd_dq:-MMG7jqP300NokKCd_dr:bk6bjf3) ([raw file](https://github.com/sachingowdaac/digital-library/blob/9d0d3c4b4acdea8f3747aea18c62119092a0716d/src/components/Home.js#L11)):*
> ```JavaScript
>         return (
>           <div
>             key={index}
> ```

using the index as the key is not the best solution, if you don't have a unique id, generate one with uuid library

**Comment by kpunith8** [comment]
___
*[src/components/Home.js, line 6 at r1](https://reviewable.io/reviews/sachingowdaac/digital-library/2#-MMG7_FK79ie2o8hl9sl:-MMG7_FK79ie2o8hl9sm:bkjp0wi) ([raw file](https://github.com/sachingowdaac/digital-library/blob/9d0d3c4b4acdea8f3747aea18c62119092a0716d/src/components/Home.js#L6)):*
> ```JavaScript
> const Home = ({ books }) => {
>   return (
>     <div className=" flex flex-wrap p-5 justify-center ">
> ```

remove the empty spaces before and after adding classname

**Comment by kpunith8** [comment]
___
*[src/components/Home.js, line 2 at r1](https://reviewable.io/reviews/sachingowdaac/digital-library/2#-MMG8cPi1TdAOMVFaHHi:-MMG8cPi1TdAOMVFaHHj:b1e27wy) ([raw file](https://github.com/sachingowdaac/digital-library/blob/9d0d3c4b4acdea8f3747aea18c62119092a0716d/src/components/Home.js#L2)):*
> ```JavaScript
> import React from 'react';
> //import Books from '../books.json';
> ```

remove the commented lines in the code

**Comment by kpunith8** [comment]
___
*[src/components/navBar.js, line 6 at r1](https://reviewable.io/reviews/sachingowdaac/digital-library/2#-MMG86K5Bn9R7C7M26sc:-MMG86K5Bn9R7C7M26sd:b-56ng83) ([raw file](https://github.com/sachingowdaac/digital-library/blob/9d0d3c4b4acdea8f3747aea18c62119092a0716d/src/components/navBar.js#L6)):*
> ```JavaScript
> const NavBar = ({ onBookSearch }) => {
>   const handleChange = (event) => {
>     event.preventDefault();
> ```

you are not submitting the form and you don't need event.preventDefault() here, you can also add a feature to submit on enter key as well

**Pull request merged**
